---
- name: Install php packages
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-gd
    - php-mysql
    - php-mbstring
    - php-process
    - php-xmlrpc
    - php-xml
    - libxslt
- name: install Hello World PHP script
  copy: src=index.php dest=/var/www/index.php mode=0664
