---
# tasks file for apache-server
- name: Install Apache
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mod_ssl
 
- name: Enable and start Apache
  systemd:
    name: httpd
    state: started
    enabled: true 
- name: Set SELinux boolean for Apache
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
